apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWprdwpNRFV5TWpKYUZ3MDBNekF4TWprd01EVXlNakphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFER1JPdXp2L0piU24vaDFiWmZRc0s5RnkrZnRGSzZCNlpqOU11MTRucmJmL2E5V0Z4dwpiM29pTGdDWStBVFpEOHAybS9waDltUG9BMVFnSzBYM3BkZ1lkcE0xQlFXbW1wRWQ5ZFJsZzBlU1BsWHlsODhtClNQTGRLcE9waWM4WldHd2YxTVRLMi82bGY3MzNHanBicU14aE1NWWVsUiszYldLYmZBNTlkVzVkNHJqN1Yyck0KSEExY2g4c25wTmo1cWJZeG92dFZHbWNxWG9ESG4zc2V4b2NEUFdJL3N3RSs2ZjVLZnVteFUzaDZTWlhBOFc1bgpzRmZ1ZDFFelFhUkUvVjdEdU4xOEh1b3E5SGUzR3RMRGppWGdTMDg1L2VkejZDZjRpSVFTMzhza01FSHJzWjU4Cnl1VzRzZVpOdU0zSUt6U01TMXlhM2Jkam9pZ0p2UTdnUktvaEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRxeDhySk9oOXFDZTZOTEJpNApnR29HOUxVSmtqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFnb0tTL2ZBQzBmak5ualNoOERKZnQ5S3R1Sk95CmI1TXcwZ0hDd1RZbXFrV3VEUS9rVFNWU0VpZU00c3B1UUg2VVVRSEdhQnJCZ1R5RW5sRjFNcmw3LzBSL3lja28KNk5wMkQ0T2wzeTI3aEwrcDFVMGtDWWFQaDF3SXJjdDdqNk45eVJkaFQyZkwxZHpIQU1aQnNiTWV2eHJWNklOVgpCdytUZTkrT2FOR3RIbVFrODFzOXFiOTQ3NHU1amNseFR4Tk04c0Q3RlVMNnRXZVVsNlJTeXhab0R6SW5VVi8wCktKeXREMTQxaG5ONzNQNkhOS0F0RlBoZE1TTTlpNXRzQUM4U29WZlN2enFZYjdldFk2bUdISzN1ODUxQUhnOEIKMUtHbHI4RGg4em5JZk5uR3dBaDJwMVpGTzBNaUdwblJ2UXJYd3ZpQWQ2c2V4RVZudFdENDcyUCtndz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34229cd8-728b-4018-976e-dc63be65b9d8.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_c6d283047be76277ad1bff1709e4ece425805224c2ee6113ef838b2a5ee04815
